import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/theme/theme-provider";

const figtree = Figtree({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vest Visuals",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${figtree.className} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
