import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "@/styles/main.css";
import ThemeProvider from "@/components/theme/theme-provider";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

const figtree = Figtree({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Vest Visuals",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${figtree.className} antialiased flex flex-col w-screen h-screen`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Navbar />
                    <div className="flex flex-col h-full max-h-full overflow-y-auto">
                        <main className="flex-grow">
                            {children}
                        </main>
                        <Footer />
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
